version: '3.7'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./database:/home/node/app/database
      - ./nodemon.json:/home/node/app/nodemon.json
    environment:
      PROD_POSTGRESS_URL: ${PROD_POSTGRESS_URL}
      POSTGRESS_URL: ${POSTGRESS_URL}
      CORS_ORIGIN: ${CORS_ORIGIN}
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: npm run dev